edit_mode = "nvim"
path = ["/Users/rmcf/.cargo/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin", "/home/rmcf/.local/share/gem/ruby/3.0.0/bin", "/home/rmcf/JAVA/jdk_15/bin", "/opt/homebrew/bin", "/home/rmcf/.deno/bin", "/usr/local/bin", "/usr/local/MacGPG2/bin"]
prompt = "starship prompt"
skip_welcome_message = true
startup = ["alias vim = nvim", "alias cp = cp -i", "alias la = exa --icons -l", "alias ls = exa ", "alias rgrep = grep -r", "alias llightmon = ~/Code/lightmon/target/debug/lightmon", "alias nakala = ~/Code/nakala/target/debug/nakala", "alias editnvim = nvim ~/.config/nvim/init.vim", "alias editnu = nvim \"/Users/rmcf/Library/Application Support/org.nushell.nu/config.toml\"", "alias gs = git status"]

[env]
ALACRITTY_LOG = "/var/folders/pt/7dhgm9m15bs_6nm63wz5t2940000gn/T/Alacritty-45458.log"
APP_SANDBOX_CONTAINER_ID = "de.codenuts.HotKey"
BROWSER = "firefox-developer-edition"
CMD_DURATION = "3.735958ms"
COLORTERM = "truecolor"
COMMAND_MODE = "unix2003"
DENO_INSTALL = "/home/rmcf/.deno"
EDITOR = "nvim"
HOME = "/Users/rmcf"
LC_ALL = "en_US.UTF-8"
LOGNAME = "rmcf"
MANPAGER = "/bin/sh -c \"col -b | nvim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""
OLDPWD = "/Users/rmcf"
PWD = "/Users/rmcf"
SHELL = "/opt/homebrew/bin/fish"
SHLVL = "1"
SSH_AUTH_SOCK = "/private/tmp/com.apple.launchd.msSBf32sSq/Listeners"
STARSHIP_SESSION_KEY = "2816405180347577"
STARSHIP_SHELL = "fish"
TERM = "screen"
TERM_PROGRAM = "tmux"
TERM_PROGRAM_VERSION = "3.2"
TMPDIR = "/var/folders/pt/7dhgm9m15bs_6nm63wz5t2940000gn/T/"
TMUX = "/private/tmp/tmux-501/default,45461,0"
TMUX_PANE = "%0"
TMUX_PLUGIN_MANAGER_PATH = "/Users/rmcf/.tmux/plugins/"
USER = "rmcf"
VISUAL = "nvim"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "application.io.alacritty.454291.454301.7C18402C-457B-4194-A290-ACE47AD0C77F"
__CFBundleIdentifier = "io.alacritty"
__CF_USER_TEXT_ENCODING = "0x1F5:0x0:0x0"
